baseURL: "https://yeasin50.github.io/yt/"
languageCode: "en-us"
title: "@yt.yeasin50"
theme: "PaperMod"

outputs:
  home: ["HTML", "JSON"]

markup:
  goldmark:
    renderer:
      unsafe: true

# Menu (top-level)
menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Learn"
      url: "/course"
      weight: 2

    - name: "Search"
      url: "/search"
      weight: 2


    - name: "About"
      url: "/about"
      weight: 99

# Theme params
params:
  # author: "Md. Yeasin Sheikh"
  description: "A website showcasing my YouTube videos"
  favicon: "images/favicon.png"

  # Enable search
  enableSearch: true
  showSearchButton: true

  # Homepage layout & main sections
  mainSections: ["posts"]
  showReadingTime: false
  showAuthor: false
  themeColor: "blue"
  showTags: true
  ShowPostNavLinks: true

  home_sections:
    - section: "posts"
      title: "Latest Videos"
      weight: 1

  customCSSFiles:
    - "css/category-card.css"
    - "css/playlist.css"

  # Social links
  social:
    website: "https://yeasin50.github.io/portfolio/"
    github: "https://github.com/yeasin50"
    youtube: "https://youtube.com/channel/yt.yeasin50"
    stackOverflow: "https://stackoverflow.com/users/10157127/"
    linkedin: "https://linkedin.com/in/mdyeasinsheikh"

  # Fuse.js search options
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  # Optional features
  enableComments: true
  dateFormat: "Jan 2, 2006"
  highlightStyle: "monokai"
