name: Deploy Hugo site to GitHub Pages

# Trigger on push or merge to master
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.150.0"  # match your local Hugo version
          extended: true            # if you use Hugo Extended (PaperMod usually does)

      # 3️⃣ Build the site
      - name: Build
        run: hugo --minify

      # 4️⃣ Deploy to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # built-in token, no need to create one
          publish_dir: ./public
          force_orphan: true                         # optional: force orphan branch
