name: Auto Merge Approved PRs

on:
  pull_request_review:
    types: [submitted]

jobs:
  merge:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Setup GitHub CLI
        uses: github/cli-action@v2

      - name: Merge PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          gh pr merge $PR_NUMBER --merge --auto
